version: '3.1'
services:
  web:
    image: danematt85/im:latest
    build:
      context: .
      dockerfile: docker/apache/Dockerfile   
    ports:
      - "80:80"
    depends_on:
      - db
    tty: true
    stdin_open: true
    environment:      
      MYSQL_DATABASE: inventory_manager
      MYSQL_USER: inventory_user
      MYSQL_PASSWORD: 7eJ{"tt66AbU(_Vn
      MYSQL_HOST: db

  db:    
    image: mysql:5.7
    restart: always
    environment:      
      MYSQL_DATABASE: inventory_manager
      MYSQL_USER: inventory_user
      MYSQL_PASSWORD: 7eJ{"tt66AbU(_Vn
      MYSQL_ROOT_PASSWORD: A6#JajRA^f@@hnD
    volumes:
      - ./docker/mysql/data:/var/lib/mysql      
      - ./docker/mysql/init:/init   
    ports:
      - "3306:3306"
    entrypoint: ["bash", "-c", "chmod +x /init/start.sh && /init/start.sh"]
    